config/routes.rb
Rails.application.routes.draw do
  get 'meta_frames/index'
  get 'meta_frames/:id', to: 'meta_frames#show',as: :meta_frame
  get 'meta_frames/:id/select', to: 'meta_frames#select'
  get 'meta_frames/:id/gif', to: 'meta_frames#gif', as: :meta_frame_gif
  get 'meta_frames/:id/edited_gif/new', to: 'edited_gifs#new', as: :edited_gif_new
  post 'meta_frames/:id/edited_gif/create', to: 'edited_gifs#create', as: :edited_gif_create
  get 'meta_frames/:id/edited_gif/:edited_gif_id', to: 'edited_gifs#show', as: :edited_gif_show
  root to: 'meta_frames#index'
end

app/models/meta_frame.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: meta_frames
#
#  id         :integer          not null, primary key
#  movie_id   :integer
#  start_sec  :float            not null
#  end_sec    :float            not null
#  text       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

require 'elasticsearch/model'
require 'google/cloud/storage'

module Searchable
  extend ActiveSupport::Concern

  included do # rubocop:disable Metrics/BlockLength
    include Elasticsearch::Model

    settings index: {
      number_of_shards: 1,
      number_of_replicas: 0,
      analysis: {
        tokenizer: {
          ja_normal_tokenizer: {
            type: 'kuromoji_tokenizer',
            mode: 'normal'
          },
          base_form_tokenizer: {
            type: 'kuromoji_tokenizer'
          }
        },
        analyzer: {
          ja_normal_analyzer: {
            type: 'custom',
            tokenizer: 'ja_normal_tokenizer'
          },
          base_form_analyzer: {
            tokenizer: 'kuromoji_tokenizer',
            filter: [
              'kuromoji_baseform'
            ]
          }
        }
      }
    } do
      mapping dynamic: 'false' do
        indexes :text, type: 'text', analyzer: 'ja_normal_analyzer'
        indexes :base_form, type: 'text', analyzer: 'base_form_analyzer'
      end
    end

    # @param words [Array[Synonym]]
    def self.search(words)
      must_params = []
      words.each do |word|
        should_params = []
        should_params << { terms: { base_form: [word.base_word], boost: 2 } }
        should_params << { terms: { base_form: word.synonym_words } } unless word.synonym_words.nil?
        must_params << { bool: { should: should_params } }
      end
      param = { query: { bool: { must: must_params } } }
      __elasticsearch__.search(param)
    end

    def self.synonym_search(words)
      synonyms = []
      mecab = Natto::MeCab.new
      words.each do |word|
        synonyms += Synonym.get_synonym_and_tokenize(word, mecab)
      end
      MetaFrame.search(synonyms)
    end
  end
end

class MetaFrame < ApplicationRecord
  include Searchable

  belongs_to :movie

  def as_indexed_json(_options = {})
    { base_form: text }
  end

  # @return [string]
  def cloud_image_path
    "#{root_path}/screenshot/#{image_num}.png"
  end

  # @return [string]
  def cloud_gif_path
    "#{root_path}/gif/#{image_num}.gif"
  end

  # @return [string]
  def image_url
    "http://#{Settings.bucket_name}/#{cloud_image_path}"
  end

  # @return [string]
  def gif_url
    "http://#{Settings.bucket_name}/#{cloud_gif_path}"
  end

  # @return [string]
  def root_path
    "#{movie.season.siry.identifier}/#{movie.season.serial}/#{movie.ep_num}"
  end

  def description_text
    "[#{movie.season.siry.name}]#{text}"
  end

  # @param local_gif_path [string]
  # @param bucket [Google::Cloud::Storage::Bucket]
  def upload_gif(local_gif_path, bucket)
    file = bucket.create_file(local_gif_path, cloud_gif_path)
    file.acl.public!
  end

  # @param local_image_path [string]
  # @param bucket [Google::Cloud::Storage::Bucket]
  def upload_image(local_image_path, bucket)
    file = bucket.create_file(local_image_path, cloud_image_path)
    file.acl.public!
  end

  # @param bucket [Google::Cloud::Storage::Bucket]
  def delete_image(bucket)
    file = bucket.find_file(cloud_image_path)
    file.delete
  end

  # @param bucket [Google::Cloud::Storage::Bucket]
  def delete_gif(bucket)
    file = bucket.find_file(cloud_gif_path)
    file.delete
  end
end

app/controllers/meta_frames_controller.rb
# frozen_string_literal: true

class MetaFramesController < ApplicationController
  def index # rubocop:disable Metrics/MethodLength
    words = words_params
    @search_form = SearchForm.new(words: words, page: params[:page])
    @meta_frames = @search_form.search
    @view_meta_frames = convert_view_metaframe(@meta_frames)
    @example_words = Settings.example_words
    @search_words = words.join(' ')
    title = "#{@search_words}の検索結果"
    @html_meta = HTMLMeta.new(title: title, description: title)
    @image_paths = { twitter: view_context.image_path('twitter.png'),
                     loading: view_context.image_path('loading.gif') }

    respond_to do |format|
      format.html
      format.json do
        render json: @view_meta_frames
      end
    end
  end

  def show
    @meta_frame = MetaFrame.find(params[:id])
    @html_meta = HTMLMeta.new(description: @meta_frame.description_text,
                              image_url: @meta_frame.image_url,
                              twitter_card: 'summary_large_image')
  end

  def select
    @meta_frame = MetaFrame.find(params[:id])
  end

  def gif
    @meta_frame = MetaFrame.find(params[:id])
  end

  private

  def convert_view_metaframe(meta_frames)
    meta_frames.includes(movie: [season: [:siry]]).map do |meta|
      { gif_path: Rails.application.routes.url_helpers.meta_frame_gif_path(meta.id),
        image_url: meta.image_url,
        gif_url: meta.gif_url,
        id: meta.id }
    end
  end

  def words_params
    return ['了解'] if params[:words].blank?

    word = params[:words]
    word.split(/[[:blank:]]+/)
  end
end

class SearchForm
  include ActiveModel::Model

  attr_accessor :words, :page

  validate :custom_validate

  def custom_validate
    return if words.blank?

    words.each do |word|
      errors.add(:words, '記号は入力できません') unless word =~ /\A[ぁ-んァ-ンーa-zA-Z0-9一-龠０-９\-\r]+\z/
    end
  end

  # @return [Array<MetaFrame>]
  def search
    return Kaminari.paginate_array([]).page(1) if invalid? || words.blank?

    MetaFrame.synonym_search(words).page(page).records(includes: { movie: { season: :siry } })
  end
end

app/helpers/meta_frames_helper.rb
module MetaFramesHelper
end

app/views/meta_frames/gif.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="mx-auto col-md-6">
      <ul class="share_buttons">
        <li>
          <a href="https://twitter.com/share?text=&url=<%= url_for(only_path: false) %>" data-size="large" class="twitter-share-button" data-show-count="false">
            <%= image_tag 'twitter.png' %>
          </a>
        </li>
        <li>
          <button type="button" class="btn btn-primary" onClick="urlCopy('<%= url_for(only_path: false) %>')">URLをコピー</button>
        </li>
      </ul>
    </div>
  </div>

  <div class="row">
    <div class="mx-auto col-md-6">
      <%= image_tag(@meta_frame.gif_url, :class => "img-fluid", :alt => "Responsive image") %>
    </div>
  </div>
  <div class="row mt-3 justify-content-md-center">
    <div class="col col-md-2">
      <button onclick="window.location.href='<%= meta_frame_path(@meta_frame) %>'" class="btn btn-primary">画像で見る</button>
    </div>
    <div class="col col-md-2">
      <button onclick="window.location.href='<%= edited_gif_new_path(@meta_frame) %>'" class="btn btn-primary">GIFの範囲を指定する</button>
    </div>
  </div>
</div>

app/views/meta_frames/index.html.erb
<div class="container">
  <div class="example_words">
    <p class="title">例から検索</p>
    <ul class="list-inline words">
      <% @example_words.each do |word| %>
        <li class="list-inline-item">
          <%= link_to word, { controller: 'meta_frames', action: 'index', words: word },{ class: 'word' } %>
        </li>
      <% end %>
    </ul>
  </div>

  <% if @search_form && @search_form.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @search_form.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= react_component('Index', { meta_frames: @view_meta_frames,
                                            image_paths: @image_paths }) %>
</div>

app/views/meta_frames/select.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-md-6">
      <%= image_tag(@meta_frame.image_url, :class => "img-fluid", :alt => "Responsive image") %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="mx-auto col-md-6">
      <%= image_tag(@meta_frame.gif_name, :class => "img-fluid", :alt => "Responsive image") %>
    </div>
  </div>
</div>

app/views/meta_frames/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <ul class="share_buttons">
        <li>
          <a href="https://twitter.com/share?text=&url=<%= url_for(only_path: false) %>" data-size="large" class="twitter-share-button" data-show-count="false">
            <%= image_tag 'twitter.png' %>
          </a>
        </li>
        <li>
          <button type="button" class="btn btn-primary" onClick="urlCopy('<%= url_for(only_path: false) %>')">URLをコピー</button>
        </li>
      </ul>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <%= image_tag(@meta_frame.image_url, :class => "img-fluid", :alt => "Responsive image") %>
    </div>
  </div>
</div>