config/routes.rb
Rails.application.routes.draw do
  get 'meta_frames/index'
  get 'meta_frames/:id', to: 'meta_frames#show',as: :meta_frame
  get 'meta_frames/:id/select', to: 'meta_frames#select'
  get 'meta_frames/:id/gif', to: 'meta_frames#gif', as: :meta_frame_gif
  get 'meta_frames/:id/edited_gif/new', to: 'edited_gifs#new', as: :edited_gif_new
  post 'meta_frames/:id/edited_gif/create', to: 'edited_gifs#create', as: :edited_gif_create
  get 'meta_frames/:id/edited_gif/:edited_gif_id', to: 'edited_gifs#show', as: :edited_gif_show
  root to: 'meta_frames#index'
end

app/models/edited_gif.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: edited_gifs
#
#  id            :integer          not null, primary key
#  file_name     :string
#  meta_frame_id :integer
#  start_frame   :integer
#  end_frame     :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class EditedGif < ApplicationRecord
  belongs_to :meta_frame

  # @return [string]
  def cloud_url
    'http://' + Settings.bucket_name + '/' + cloud_path
  end

  # @return [string]
  def cloud_path
    meta_frame.root_path + '/edited_gif' + '/' + file_name + '.gif'
  end

  def upload_image(local_path)
    storage = Google::Cloud::Storage.new(project_id: Settings.gcp_project_id, credentials: Settings.gcp_credentials)
    bucket = storage.bucket Settings.bucket_name
    file = bucket.create_file(local_path, cloud_path)
    file.acl.public!
  end
end

app/controllers/edited_gifs_controller.rb
# frozen_string_literal: true

class EditedGifsController < ApplicationController
  def new
    @meta_frame = MetaFrame.find(params[:id])
  end

  def show
    @meta_frame = MetaFrame.find(params[:id])
    @edited_gif = EditedGif.find(params[:edited_gif_id])
  end

  def create # rubocop:disable Metrics/AbcSize
    meta_frame = MetaFrame.find(params[:id])

    form = CreateForm.new(start_frame: params['gif_length']['start_frame'].to_i,
                          end_frame: params['gif_length']['end_frame'].to_i)
    edited_gif = form.create(meta_frame)

    if form.errors.any?
      redirect_to action: 'new', id: meta_frame.id
    else
      redirect_to action: 'show', id: meta_frame.id, edited_gif_id: edited_gif.id
    end
  end
end

class CreateForm
  include ActiveModel::Model
  attr_accessor :start_frame, :end_frame

  validates :start_frame, :end_frame, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }

  # @return [EditedGif]
  def create(meta_frame)
    file_name = SecureRandom.urlsafe_base64
    local_path = "tmp/edited_gif/#{file_name}.gif"
    cut_gif(meta_frame, local_path)
    edited_gif = EditedGif.new(meta_frame: meta_frame, start_frame: start_frame, end_frame: end_frame, file_name: file_name)
    edited_gif.upload_image(local_path)
    File.delete(local_path)
    edited_gif.save!
    edited_gif
  end

  private

  def cut_gif(meta_frame, local_path)
    FileUtils.mkdir_p('tmp/edited_gif') unless File.exist?('tmp/edited_gif')
    system('wget', "http://#{Settings.bucket_name}/#{meta_frame.cloud_gif_path}")
    option = "trim=start_frame=#{start_frame}:end_frame=#{end_frame + 1},setpts=PTS-STARTPTS,scale=640:-1,split[a][b];[a]palettegen[pal];[b][pal]paletteuse"
    system('ffmpeg', '-i', "#{meta_frame.image_num}.gif", '-vf', option, local_path)
    system('rm', "#{meta_frame.image_num}.gif")
  end
end

app/views/edited_gifs/new.html.erb
<div class="container-fluid">
  <div class="row">
      <div class="mx-auto col-md-6">
        <img id="example1">
      </div>
  </div>
  <div class="row">
    <div class="mx-auto col-md-6" id="gif_range">
      Gifの範囲を指定する:<br>
      <div id="slider">
      </div>
    </div>
  </div>
  <div class="row mt-3">
    <div class="mx-auto">
      <%= form_tag edited_gif_create_path(@meta_frame),:method => :post do |f| %>
        <%= hidden_field :gif_length,:start_frame,id: :start_frame %>
        <%= hidden_field :gif_length,:end_frame,id: :end_frame %>
        <%= submit_tag "Create" ,:id => "submit_button",:disabled => "disabled",class: "btn btn-primary"%>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript" src="/js/libgif/libgif.js"></script>
<script type="text/javascript" src="/js/libgif/rubbable.js"></script>
<script type="text/javascript" src="/js/nouislider.js"></script>
<script>
    var min_value = 0;
    var max_value = 0;
    function load_slider() {
        var slider = document.getElementById('slider');
        noUiSlider.create(slider, {
            start: [0, sup1.get_length()],
            connect: true,
            range: {
                'min': 0,
                'max': sup1.get_length()
            },
            step:1
        });

        slider.noUiSlider.on('update', function (values, handle) {
            min_value = values[0];
            max_value = values[1];

            var element = document.getElementById("start_frame");
            element.setAttribute("value", min_value);
            var element = document.getElementById("end_frame");
            element.setAttribute("value", max_value);
            var element = document.getElementById("submit_button");
            element.removeAttribute("disabled");
        });

        max_value = sup1.get_length();
    }

    var sup1 = new SuperGif({
        gif: document.getElementById('example1'), step_func: function (gif) {
            current_frame = sup1.get_current_frame()
            if(!(min_value < current_frame && current_frame < max_value)){
                sup1.move_to(min_value)
            }
        }, on_end: function (gif) {
            sup1.move_to(min_value)
        }
    });
    sup1.load_url("<%= @meta_frame.gif_url %>",load_slider);
</script>

app/views/edited_gifs/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="mx-auto col-md-6">
      <ul class="share_buttons">
        <li>
          <a href="https://twitter.com/share?text=&url=<%= url_for(only_path: false) %>" data-size="large" class="twitter-share-button" data-show-count="false">
            <%= image_tag 'twitter.png' %>
          </a>
        </li>
        <li>
          <button type="button" class="btn btn-primary" onClick="urlCopy('<%= url_for(only_path: false) %>')">URLをコピー</button>
        </li>
      </ul>
      <%= image_tag(@edited_gif.cloud_url, :class => "img-fluid", :alt => "Responsive image") %>
    </div>
  </div>
</div>